### ISSUE TITLE
Bug // Accès au souterrain

### ISSUE THREAD

**Issue by Seg0go** [rootasjey/brexity#2]
Lorsque l'on appuie sur E pour accéder au sous-terrain, un écran bleu s'affiche cf : image 
![blue_screnn_sousterrain](https://user-images.githubusercontent.com/37019869/36935434-ff2d3052-1ef7-11e8-9329-60c67403c35e.png)

**Comment by rootasjey** [comment]
Fixed in https://github.com/rootasjey/brexity/commit/c50469b5d0941719c7d9174b05a285090f6ae0d8
